FizzBuzz/FizzBuzz/Models/ConfigSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Configuration;

namespace FizzBuzz.Models
{
    public  static class ConfigSettings
    {
        public static int FizzBuzzMinValue
        {
            get { return int.Parse(ConfigurationManager.AppSettings["FizzBuzzMinValue"]); }
        }

        public static int FizzBuzzMaxValue
        {
            get { return int.Parse(ConfigurationManager.AppSettings["FizzBuzzMaxValue"]); }
        }

        public static int PageSize
        {
            get { return int.Parse(ConfigurationManager.AppSettings["PageSize"]); }
        }
    }
}

FizzBuzz/FizzBuzz/Models/FizzBuzzItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Drawing;
namespace FizzBuzz.Models
{
    public class FizzBuzzItem :IFizzBuzzItem
    {
        public FizzBuzzItem(int fizzBuzzNumber, string displayText, Color color )
        {
            Index = fizzBuzzNumber;
            Text = displayText;
            this.Color = color;
        }

        public string Text { get; private set; }
        public Color Color { get; private set; }
        public int Index { get; private set; }
    }
}

FizzBuzz/FizzBuzz/Models/FizzBuzzModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Drawing;
using System.ComponentModel.DataAnnotations;

namespace FizzBuzz.Models
{
    public class FizzBuzzModel
    {
        public FizzBuzzModel()
        {

        }

        /// <summary>
        /// Gets the FizzBuzz result
        /// </summary>
        /// <returns>IFizzBuzzItem Collection</returns>
        public IEnumerable<IFizzBuzzItem> GetFizzBuzz()
        {
            if (FizzBuzzCount < ConfigSettings.FizzBuzzMinValue || FizzBuzzCount > ConfigSettings.FizzBuzzMaxValue)
            {
                throw new InvalidOperationException();
            }
            List<IFizzBuzzItem> fizzBuzz = new List<IFizzBuzzItem>();
            int i;
            bool isWednesday = false;
            if (DateTime.Now.DayOfWeek == DayOfWeek.Wednesday)
            {
                isWednesday = true;
            }
            for (i = 1; i <= FizzBuzzCount; i++)
            {
                bool isFizz = false;
                bool isBuzz = false;               
                IFizzBuzzItem item = null;
                string fizzOrBuzz = string.Empty;
                if(i % 3 == 0)
                {
                    if (isWednesday)
                    {
                         item = new FizzBuzzItem(i, "wizz", Color.Blue);
                    }
                    else
                    {
                        item = new FizzBuzzItem(i, "fizz", Color.Blue);
                    }
                    isFizz = true;
                }

                if(i % 5 == 0)
                {
                    if (isWednesday)
                    {
                         item = new FizzBuzzItem(i, "wuzz", Color.Green);
                    }
                    else
                    {
                        item = new FizzBuzzItem(i, "buzz", Color.Green);
                    }
                   
                    isBuzz = true;
                }

                if (isFizz && isBuzz)
                {
                    if (isWednesday)
                    {
                        item = new FizzBuzzItem(i, "wizz wuzz", Color.Black);
                    }
                    else
                    {
                        item = new FizzBuzzItem(i, "fizz buzz", Color.Black);
                    }                    
                }

                if(!isFizz && !isBuzz)
                {
                    item = new FizzBuzzItem(i,i.ToString(), Color.Black);
                }

                fizzBuzz.Add(item);
            }

            return fizzBuzz.AsEnumerable<IFizzBuzzItem>();
        }

        [Required]
        [Range(1,900)]
        public int FizzBuzzCount { get; set; }
        
        
    }
   
}

FizzBuzz/FizzBuzz/Models/IFizzBuzzItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Drawing;

namespace FizzBuzz.Models
{
    public interface IFizzBuzzItem: IItem
    {
        string Text { get;  }
        Color Color { get;  }
        

    }
}

FizzBuzz/FizzBuzz/Models/IItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FizzBuzz.Models
{
   public  interface IItem
    {
       int Index { get; }
    }
}

FizzBuzz/FizzBuzz/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FizzBuzz.Models
{
    public class Item : IItem
    {
        public Item(int Index)
        {
            this.Index = Index;
        }

        public int Index { get; private set; }
    }
}

FizzBuzz/FizzBuzz/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FizzBuzz.Models;
using PagedList.Mvc;
using PagedList;
using System.Configuration;
using System.Web.Mvc.ExpressionUtil;

namespace FizzBuzz.Controllers
{
     [HandleError(ExceptionType = typeof(InvalidOperationException), View = "InvalidInputErrorView")]
    public class FizzBuzzController : Controller
    {
        //
        // GET: /FizzBuzz/

        [HttpGet]
        public ActionResult Index()
        {
            return View("DefaultView");
        }


        /// <summary>
        /// Gets the FizzBuzz result for the user input.
        /// </summary>
        /// <param name="userInput">UserInput</param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        public ActionResult GetFizzBuzz(FizzBuzzModel fizzBuzzModel)
        {
            IEnumerable<IFizzBuzzItem> fizzBuzzItems = null;
            int pageSize = ConfigSettings.PageSize;
            int pageIndex = 1;                                           
            fizzBuzzItems = fizzBuzzModel.GetFizzBuzz();
            ViewBag.FizzBuzzCount = fizzBuzzModel.FizzBuzzCount;
            
            return View("FizzBuzzView", fizzBuzzItems.ToPagedList<IFizzBuzzItem>(pageIndex, pageSize)); // View FizzBuzz Result for the first Page
        }


        /// <summary>
        /// Gets FizzBuzz result for the selected page.
        /// </summary>
        /// <param name="page">Integer</param>
        /// <param name="FizzBuzzCount">Integer</param>
       
        public ActionResult Paging(int? page, int? FizzBuzzCount)
        {
            IEnumerable<IFizzBuzzItem> fizzBuzzItems = null;
            int pageSize = ConfigSettings.PageSize;
            int pageIndex = 1;
                          
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            FizzBuzzModel model = new FizzBuzzModel();
            model.FizzBuzzCount = FizzBuzzCount.Value;
            fizzBuzzItems = model.GetFizzBuzz();
            ViewBag.FizzBuzzCount = FizzBuzzCount.Value;
            
            return View("FizzBuzzView", fizzBuzzItems.ToPagedList<IFizzBuzzItem>(pageIndex, pageSize)); // View the page selection changes
        }
                
    }
}

FizzBuzz/FizzBuzz/Views/FizzBuzz/DefaultView.cshtml
@model FizzBuzz.Models.FizzBuzzModel

@{
    ViewBag.Title = "Fizz Buzz";

}

<h2>Fizz Buzz </h2>
<br />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/_references.js")

}


@using (Html.BeginForm("GetFizzBuzz", "FizzBuzz", FormMethod.Post))
{
    <table class="default1">
        <tr>
            <td> Fizz Buzz Count</td>
            <td> @Html.TextBoxFor(m => m.FizzBuzzCount)  (1-900)</td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" id="btnSubmit" value="Submit" /></td>
        </tr>
    </table>

}

FizzBuzz/FizzBuzz/Views/FizzBuzz/FizzBuzzView.cshtml
@using FizzBuzz.Models;
@using PagedList.Mvc;

@model PagedList.IPagedList<FizzBuzz.Models.IFizzBuzzItem>

@{
    ViewBag.Title = "FizzBuzz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <h2>FizzBuzz Result               </h2>
    <h5>   Today is @DateTime.Now.DayOfWeek.ToString()!  @Html.ActionLink("Home", "Index") </h5>
    <h3><u>You have entered  value @ViewBag.FizzBuzzCount!</u></h3>
    <table class="result">
        <tr>
            <td class="resultth"> <h4>Numbder</h4> </td>
            <td class="resultth"> <h4> Fizz Buzz Status </h4></td>
        </tr>
        @{
    foreach (var fizzBuzzItem in Model)
    {

        <tr>
            <td class="resultth">@fizzBuzzItem.Index</td>
            <td class="resultth"><label title="@fizzBuzzItem.Text" style="color:@fizzBuzzItem.Color.Name">@fizzBuzzItem.Text</label></td>
        </tr>

    }
        }

    </table>
    <table class="paging">
        <tr>
            <td>
                <div id='Paging' style="text-align:center">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                    of @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("Paging", new { page, ViewBag.FizzBuzzCount }), PagedListRenderOptions.MinimalWithPageCountText)
                </div>

            </td>
        </tr>
    </table>

}

FizzBuzz/FizzBuzz/Views/FizzBuzz/InvalidInputErrorView.cshtml
@{
    ViewBag.Title = "FizzBuzz - Invalid Input";
}

<h2>FizzBizz Exception</h2>
<h3> <label style="color:red" >
     Error: Invalid FizzBuzz value. Value should be between @FizzBuzz.Models.ConfigSettings.FizzBuzzMinValue and @FizzBuzz.Models.ConfigSettings.FizzBuzzMaxValue.
    </label></h3>
<h5>@Html.ActionLink("Home", "Index")</h5>

FizzBuzz/FizzBuzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>